version: 2

base_image: &base_image
  image: circleci/node:6.11.1

job_common: &job_common
  docker:
    - <<: *base_image

restore: &restore
  restore_cache:
    key: code-{{ .Revision }}

store_artifacts: &store_artifacts
  store_artifacts:
    path: output
    destination: /

jobs:
  build:
    <<: *job_common
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "package.json" }}
      - run: ./scripts/install-ci.sh
      - save_cache:
          key: deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: yarn run compile
      - save_cache:
          key: code-{{ .Revision }}
          paths:
            - .

  release:
    <<: *job_common
    steps:
      - <<: *restore
      - run: mkdir -p ~/.ssh
      - run: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: yarn config set registry https://registry.npmjs.org/
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run: git config --global user.email "donvoy@convoy.com"
      - run: git config --global user.name "Don Voy"
      - run: yarn run release
      - <<: *store_artifacts

workflows:
  version: 2
  build-test-release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - /v\d+\.\d+/
